on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - name: print name
        run: echo "I'm" ${{ inputs.name }}
