on:
  workflow_call:
    inputs:
      first_name:
        required: true
        type: string
    secrets:
      last_name:
        required: true

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - name: print name
        run: echo "I'm" ${{ inputs.first_name }}
